### ISSUE TITLE
How can we reach the cpx-ingress-controller on 443 ?

### ISSUE THREAD

**Issue by mleneveut** [netscaler/netscaler-helm-charts#191]
Hello,

We used the helm chart nsic-v1.43.7 to deploy an netscaler-ingress-controller and netscaler-cpx-with-ingress-controller linked to a Netscaler.

We want to use SSL between the Netscaler and the CPX inside the Kubernetes (security prerequisites from our sec team)

How could we do that ? The cpx pod doesn't seem to listen to 443 at all.

Thanks.

**Comment by subashd** [comment]
hi @mleneveut ,
Ports[ 80 and 443](https://github.com/netscaler/netscaler-helm-charts/blob/1ee3dd94d874dde5d18bfa8b07d1057524a39ccf/netscaler-cpx-with-ingress-controller/templates/deployment.yaml#L437) of CPX service are exposed. While deploying in the Kubernetes, you can expose the service of CPX as type NodePort. The NetScaler Ingress Controller ( NSIC) configuring the NetScaler will automatically updates the IP and Port for CPX ( NodeIP and NodePort of the node where CPX pod is running), if you provided CPX service as backend service in Ingress YAML.

To expose service of CPX as NodePort:
https://github.com/netscaler/netscaler-helm-charts/tree/master/netscaler-cpx-with-ingress-controller#netscaler-cpx-servicetype-nodeport



Sample Ingress for configuring NetScaler.
```
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name:  netingress
  annotations:
    ingress.citrix.com/frontend-ip: <VIP>
spec:
  ingressClassName: <ingressclass>
  tls:
    - hosts:
        - <host>
       secretName: <TLS Secret >
  rules:
    - host: <host>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: <service name of CPX> 
                port:
                  number: 443
```

**Comment by mleneveut** [comment]
Thanks for your answer @subashd 

I filled the questionnaire.

We would like to call this Ingress on 443 so that the request from Netscaler to CPX is secured : 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.citrix.com/frontend-ip: 10.x.x.15
    ingress.citrix.com/secure-service-type: ssl
    ingress.citrix.com/secure_backend: "True"
  name: cpx-ingress
  namespace: netscaler
spec:
  ingressClassName: tier-1-vpx
  rules:
  - host: testapp.mycomp.com
    http:
      paths:
      - backend:
          service:
            name: netscaler-cpx-with-ingress-controller-cpx-service
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - secretName: testapp-tls-secret
```

But the netscaler-cpx-with-ingress-controller-cpx-service then tries to reach the netscaler-cpx-with-ingress-controller pod on port 443 and it doesn't work, as this pod only listens to 80. We have a connection reset when calling https://testapp.mycomp.com

The netscaler-cpx-with-ingress-controller-cpx-service is exposed with NodePort : 

```
spec:
  clusterIP: 10.90.21.186
  clusterIPs:
  - 10.90.21.186
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30868
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 31963
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: netscaler-cpx-with-ingress-controller
  sessionAffinity: None
  type: NodePort
```

To have a secured connection between Netscaler and CPX we want to use the 31963 port in Netscaler (the service group member use the nodePort 31963)

If we set the CPX ingress to : 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.citrix.com/frontend-ip: 10.x.x.15
    ingress.citrix.com/secure-service-type: ssl
    ingress.citrix.com/secure_backend: "True"
  name: cpx-ingress
  namespace: netscaler
spec:
  ingressClassName: tier-1-vpx
  rules:
  - host: testapp.mycomp.com
    http:
      paths:
      - backend:
          service:
            name: netscaler-cpx-with-ingress-controller-cpx-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - secretName: testapp-tls-secret
```

all is green in Netscaler but it uses the nodePort 80:31357/TCP.


What configuration would create all Netscaler resource as SSL and using a ServiceGroup Member using 443:30323/TCP NodePort to enter the cluster ?
